### ISSUE TITLE
Consider which deployment files should be ignored within git

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-frontend#6]
Almost certainly files under `dist/` and `node_modules/` should be included in the a `.gitignore` so that the git repository is only tracking local source code changes.  The dependencies and the packaged application should only exist in deployed packages (releases), or left to the administrator to deploy when the application is installed.

To capture the state of the the application when it has been tested with specific dependencies, you will want to include the `package-lock.json` file in the git repository.  If specific dependency versions are non-critical, you may want to exclude the `package-lock.json` file via the `.gitignore`.

For configuration files where the administrator who is deploying the application has choices to make (such as database names, passwords, backend hostnames, ports, etc.), the git repo should provide sample files or sample values, with instructions to the administrator for changes.  For example, consider `src/environments/environment.prod.ts`.

**Comment by Xiaoxin-He** [comment]
- [x] `gitignore` is updated with including dist/ folder, so will not be included with the source code.
- [x] I would like to keep `package-lock.json` since I could keep track of versions changes or updates during implementation.
- [x] since the API root of `src/environments/environment.prod.ts` is the same as which backend service is running on and pointing to the server, so we just need the API ROOT key for the environment on the front-end, (comment is included)

**Comment by ctgraham** [comment]
I think this issue is almost resolved, but we still need to remove the `node_modules` directory itself from the repo.

**Comment by Xiaoxin-He** [comment]
node_modules is updated in git ignore

**Comment by ctgraham** [comment]
Confirmed.
